project:
  type: website
  output-dir: docs

website:
  title: "Forecasting cash rate"
  favicon: fcr.png
  navbar:
    background: "light"
    right:
      - icon: person
        url: https://github.com/donotdespair
      - icon: github
        url:  https://github.com/forecasting-cash-rate/forecasting-cash-rate.github.io
      - icon: linkedin
        url: https://www.linkedin.com/in/tomasz-wo%C5%BAniak-7b85361b1/
      - icon: cloud-fill
        url: https://bsky.app/profile/tomaszwozniak.bsky.social
      - icon: mastodon
        url: https://fosstodon.org/@tomaszwozniak
      - icon: envelope
        href: mailto:twozniak@unimelb.edu.au
  sidebar:
    logo: fcr.png
    style: "floating"
    search: true
    contents:
      - file: index.qmd
        text: "RBA Cash Rate Survey Forecasts"
      - section: "2024"
        contents:
          - file: 2024_06.qmd
            text: "Early June"
          - file: 2024_04.qmd
            text: "Late April"
          - file: 2024_03.qmd
            text: "Early March"
          - file: 2024_01.qmd
            text: "January"
      - section: "2023"
        contents:
          - file: 2023_12.qmd
            text: "December"
          - file: 2023_11.qmd
            text: "November"
          - file: 2023_10.qmd
            text: "October"
          - file: 2023_09.qmd
            text: "September"
          - file: 2023_08.qmd
            text: "August"
          - file: 2023_07.qmd
            text: "July"
          - file: 2023_06.qmd
            text: "June"
          - file: 2023_05.qmd
            text: "May"
          - file: 2023_04.qmd
            text: "April"
          - file: 2023_03.qmd
            text: "March"
          - file: 2023_02.qmd
            text: "February"
          - file: 2023_01.qmd
            text: "January"
      - section: "2022"
        contents:
          - file: 2022_11.qmd
            text: "November"
          - file: 2022_10.qmd
            text: "October"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true