{
  "hash": "f7bb969de2c7373600dff2d5cf3cbcf0",
  "result": {
    "markdown": "---\ntitle: \"July 2023\"\nauthor: \n  - name: \"Tomasz Woźniak\"\n    url: https://github.com/donotdespair\n    affiliations:\n      - University of Melbourne\n    orcid: 0000-0003-2212-2378\nexecute:\n  freeze: auto\n---\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n> The end-of-May forecasting for the RBA cash rate survey by [finder.com.au](https://www.finder.com.au/rba-cash-rate) follows the announcement of inflation for the second quarter of 2023 at the level of 6%. The new data leads to forecasts indicating a decisive increase in the cash rate in August and likely increases further on.\n\n## Cash rate forecasts\n\nThe figure below presents the monthly cash rate series starting from January 2010, with the forecasts reported from August 2023 to July 2024 as the forecast mean and the 68% forecasting intervals.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](2023_07_files/figure-html/forecast plot-1.png){width=672}\n:::\n:::\n\n\nThe table below makes the numerical values presented in the figure more accessible.\n\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Monthly and quarterly cash rate forecasts\n\n|         | monthly| lower| upper|\n|:--------|-------:|-----:|-----:|\n|Aug 2023 |    4.24|  4.16|  4.33|\n|Sep 2023 |    4.38|  4.25|  4.55|\n|Oct 2023 |    4.52|  4.30|  4.75|\n|Nov 2023 |    4.59|  4.31|  4.87|\n|Dec 2023 |    4.65|  4.32|  4.99|\n|Jan 2024 |    4.67|  4.29|  5.09|\n|Feb 2024 |    4.73|  4.30|  5.21|\n|Mar 2024 |    4.78|  4.30|  5.31|\n|Apr 2024 |    4.81|  4.28|  5.40|\n|May 2024 |    4.82|  4.26|  5.48|\n|Jun 2024 |    4.85|  4.25|  5.56|\n|Jul 2024 |    4.85|  4.20|  5.61|\n:::\n:::\n\n\n## Survey answers\n\nBased on the forecasts above, and the analysis of forecasts from individual models, I formed the following survey answers:\n\n**When you think the RBA will change the cash rate?**\n\n|          | Aug 2023 | Sep 2023 | Oct 2023 | Nov 2023 | Dec 2023 | Feb 2023 | Mar 2024 | Apr 2024 | May 2024 or later |\n|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|\n| Increase | ✓        | ✓        | ✓        |          |          |          |          |          |                   |\n| Decrease |          |          |          |          |          |          |          |          |                   |\n\n**Why do you think this?**\n\n> My forecasts indicate a 15 basis point rise in the cash rate, with further increases up to 4.5% in October. The narrow forecast interval, spanning the values from 4.16 to 4.33% for August, leaves little doubt about the projected raises. However, the quarterly reading of year-to-year inflation at 6%, putting it on a speedy path towards the RBA's target, makes this raise somehow less likely this month. My forecasts are available at: https://donotdespair.github.io/cash-rate-survey-forecasts/\n\n**By how much do you think the RBA will change the cash rate in the next meeting?**\n\n> 15 pbs\n\n**At what level do you think the cash rate will peak?**\n\n> 4.5%\n\n**When do you think the cash rate will peak?**\n\n> October 2023\n\n## RBA's decision\n\nTBA on 1 August 2023.\n\n## Forecasting system\n\nMy forecasting system for July is based on the cash rate target and government bond yields at various maturities as presented in the figure below.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](2023_07_files/figure-html/data plot yields-1.png){width=672}\n:::\n:::\n\n\nThe system consists of a 144 of models. Half of them are are models of weekly and the other half of monthly data.\n\nVector Error Correction models for weekly and monthly series with different model specification parameters. Univariate models for the cash rate capture complex patterns of data persistence using autoregressive moving average equation extended by time-varying volatility equation - a GARCH model. Part of the models include the leverage effect and/or time-varying risk premium. \n\nThe forecasts are pooled in two stages. Firstly, the models are weighted in four sub-groups VECM vs. ARMA and weekly vs. monthly data models proportionally to their cash rate forecasting ability. Such four pooled forecasts are equally weighted in the second stage to provide monthly forecasts reported above.\n",
    "supporting": [
      "2023_07_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}