{
  "hash": "1a7c23b4c3e1446b77af605f09c5f9fe",
  "result": {
    "markdown": "---\ntitle: \"October 2023\"\nauthor: \n  - name: \"Tomasz Woźniak\"\n    url: https://github.com/donotdespair\n    affiliations:\n      - University of Melbourne\n    orcid: 0000-0003-2212-2378\nexecute:\n  freeze: auto\n---\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n> The end-of-October forecasting for the RBA cash rate survey by [finder.com.au](https://www.finder.com.au/rba-cash-rate) follows the announcement of September quarterly inflation 5.4%.\n\n## Cash rate forecasts\n\nThe figure below presents the monthly cash rate series starting from January 2010, with the forecasts reported from November 2023 to October 2024 as the forecast mean and the 68% forecasting intervals.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](2023_10_files/figure-html/forecast plot-1.png){width=672}\n:::\n:::\n\n\nThe table below makes the numerical values presented in the figure more accessible.\n\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Monthly and quarterly cash rate forecasts\n\n|         | monthly| lower| upper|\n|:--------|-------:|-----:|-----:|\n|Nov 2023 |    4.16|  4.08|  4.25|\n|Dec 2023 |    4.22|  4.08|  4.36|\n|Jan 2024 |    4.24|  4.05|  4.47|\n|Feb 2024 |    4.29|  4.03|  4.57|\n|Mar 2024 |    4.26|  3.94|  4.60|\n|Apr 2024 |    4.23|  3.85|  4.63|\n|May 2024 |    4.19|  3.75|  4.65|\n|Jun 2024 |    4.16|  3.67|  4.67|\n|Jul 2024 |    4.09|  3.55|  4.66|\n|Aug 2024 |    4.09|  3.51|  4.73|\n|Sep 2024 |    4.06|  3.43|  4.75|\n|Oct 2024 |    4.06|  3.38|  4.79|\n:::\n:::\n\n\n## Survey answers\n\nBased on the forecasts above, and the analysis of forecasts from individual models, I formed the following survey answers:\n\n**When you think the RBA will change the cash rate?**\n\n|          | Oct 2023 | Nov 2023 | Dec 2023 | Feb 2024 | Mar 2024 | Apr 2024 | May 2024 | Jun 2024 | Jul 2024 or later |\n|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|\n| Increase |          |          |          |          |          |          |          |          |                   |\n| Hold     | ✓        | ✓        |          |          |          |          |          |          |                   |\n| Decrease |          |          |          |          |          |          |          |          |                   |\n\n**Why do you think this?**\n\n> The 68% forecasting interval from my predictive system containing over two hundred models of weekly and monthly data spans the cash rate values from 4.09 to 4.25 per cent. Therefore, it includes both the HOLD and RAISE decisions. Despite the latest reading of quarterly inflation, and given the latest communication from the RBA, my choice is to indicate HOLD. My forecasts are available at: https://forecasting-cash-rate.github.io/\n\n**By how much do you think the RBA will change the cash rate in the next meeting?**\n\n> 0 pbs\n\n**At what level do you think the cash rate will peak?**\n\n> 4.1%\n\n**When do you think the cash rate will peak?**\n\n> June 2023\n\n## RBA's decision\n\nTBA.\n\n## Forecasting system\n\nMy forecasting system for September is based on the cash rate target and government bond yields at various maturities as presented in the figure below.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](2023_10_files/figure-html/data plot yields-1.png){width=672}\n:::\n:::\n\n\nThe system consists of over two hundred of models. Half of them are are models of weekly and the other half of monthly data.\n\nThe novelty starting from this month is forecasting using a foreign sector represented by monthly trade weighted indices and interest rates of Australia's closest trading partners.\n\nVector Error Correction models for weekly and monthly series with different model specification parameters. Univariate models for the cash rate capture complex patterns of data persistence using autoregressive moving average equation extended by time-varying volatility equation - a GARCH model. Part of the models include the leverage effect and/or time-varying risk premium.\n\nThe forecasts are pooled in two stages. Firstly, the models are weighted in four sub-groups VECM vs. ARMA and weekly vs. monthly data models proportionally to their cash rate forecasting ability. Such four pooled forecasts are equally weighted in the second stage to provide monthly forecasts reported above.\n",
    "supporting": [
      "2023_10_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}